#!/usr/bin/env zsh

# Author: Shane

###############################
# EXPORT ENVIRONMENT VARIABLE #
###############################

# Dotfiles
export DOTFILES="$HOME/.dotfiles"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/.local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/.cache"

# editor
export EDITOR="nvim"
export VISUAL="nvim"
export VIMCONFIG="$XDG_CONFIG_HOME/nvim"

# ZSH
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zsh_history" # History filepath
export HISTSIZE=20000                   # Maximum events for internal
export SAVEHIST=10000                   # Maximum events in history file
export HISTTIMEFORMAT="[%F %T]"

# Homebrew
export HOMEBREW_CASK_OPTS="--no-quarantine --no-binaries"
export HOMEBREW_BUNDLE_FILE="$DOTFILES/Brewfile"
export HOMEBREW_NO_ENV_HINTS

# Other Misc
export LESSHISTFILE=-
export NULLCMD='bat'
export LOCATE_CONFIG="/etc/locate.users.rc" # Locate Command's Database
export BAT_CONFIG_PATH="$XDG_CONFIG_HOME/bat/bat.conf"
export GITHUB_USER="Shaneio"
export STARSHIP_CONFIG="$DOTFILES/starship.toml"

# NVM & NPM
export NODE_REPL_HISTORY=""
export npm_config_cache="$XDG_CACHE_HOME/npm"

# FZF
# export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --glob '!.git'"
# export FZF_CTRL_T_COMMAND="FZF_DEFAULT_COMMAND"

