source "$DOTFILES/zsh/zsh-settings/aliases.zsh"
source "$DOTFILES/zsh/zsh-settings/brew.zsh"
source "$DOTFILES/zsh/zsh-settings/functions.zsh"
source "$DOTFILES/zsh/zsh-settings/fzf.zsh"
source "$DOTFILES/zsh/zsh-settings/nvim_switcher.zsh"
source "$DOTFILES/zsh/zsh-settings/preferences.zsh"

# +-------------+
# | PATH        |
# +-------------+
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"




# Starship
eval "$(starship init zsh)"
# fzf
source <(fzf --zsh)
# fasder (fasd) brew install wyne/tap/fasder
eval "$(fasder --init auto aliases)"
